const int BUFFER_SIZE = 12;
const int BUFFER_SIZE_UP = 13;
byte buf[BUFFER_SIZE];
byte buf_up[BUFFER_SIZE_UP] = {13,3,149,90,41,68,40,170, 4, 20, 1, 50,14}; // sample packet generated by the display
 
void setup() {
  //Setup serial connection
  Serial.begin(9600);
  Serial1.begin(9600);
}
 
void loop() {
  if (Serial1.available() >= BUFFER_SIZE) { // check if there are enough available bytes to read
    Serial1.readBytes(buf, BUFFER_SIZE); // read bytes to the buf array
    // prints the received data
    Serial.print("I received: ");
    for(int i = 0; i < BUFFER_SIZE; i++){
      Serial.print("B");
      Serial.print(i);
      Serial.print(": ");
      Serial.print(buf[i]);
      Serial.print(" ");
    }
    Serial.println("");
  }
  else {
    Serial1.write(buf_up, BUFFER_SIZE_UP); // if there are no available bytes send a packet to turn on the controller (it will not start without one)
  }
  delay(10);
}
